root = this

class TimesSinsData

  constructor: (@gmap) ->
    @sins_data = [{ category: "envy", url_1: "http://www.gigposters.com/forums/anything-goes/20987-mugging-times-square.html", title: "Thwarted mugging on subway platform", 
    blurb: "So my boyfriend comes home from work this morning all pissed off because he was standing on the subway platform at 42nd street and some guy hit the hand holding his briefcase with a chunk of metal, apparently hoping he'd drop it so the guy could grab it and run. But instead of dropping it, my BF just LOOKS at the guy who kind of shrugs apologetically. My guy is pretty big (and the would-be thief wasn't) so he grabs him, hauls him upstairs and hands him over to a group of cops. Now he wants to buy a car.",
    location: "Times Sq train station: intersection of 42nd Street, Seventh Avenue, and Broadway", latlong: "40.75500261555,-73.987512588501", date: "2003" },
    { category: "envy", url_1: "http://www.nytimes.com/2004/10/24/nyregion/thecity/24mugg.html?pagewanted=print&position=", title: "Richard Buggy, mugger decoy",
    blurb: "In the early 1970's, a young officer named Richard Buggy held one of the stranger and more harrowing positions in the New York Police Department. Five days a week, working a 6 p.m.-to-2 a.m. shift for the department's anticrime unit, he got mugged for a living. The anticrime unit, based on Randalls Island, was a squad of 200 plainclothes officers created, in part, to stem the city's then-endemic mugging problem, and Mr. Buggy was its star decoy. Transforming himself into a cast of assailable characters, including an old woman, a tourist, a blind man and - his showstopper - a well-lubricated drunk, he wandered the city's avenues like a wounded gazelle roaming the high plains, enticing muggers to pounce. And pounce they did. Bands of muggers worked Times Square. Renegade muggers prowled the parks and the subways. With vast swaths of the city deemed unsafe, New Yorkers hemmed themselves in. The muggers, many of them drug-sick and desperate for cash, responded by going to their victims, attacking them in elevators, hallways and darkened apartment lobbies. Even children carried &ldquo;mugger's money,'' and sharing mugging stories became fodder for dinner party conversation. Because mugging is not recorded as a separate crime (it falls under the broader umbrella of robbery), it is hard to pin down exactly how many muggings were committed in a given year. In 1968, however, to cite one example, the police in Manhattan alone received 16,200 reports of muggings, and many more were likely committed but never reported. Women and the elderly were particular targets, but muggers were never ones to discriminate. In 1974, even John F. Kennedy Jr. was mugged in Central Park, which by then had become an overgrown no man's land.",
    location: "Times Square", latlong: "40.7539460738833,-73.9869546890259", date: "1970's" },
    { category: "envy", url_1: "http://www.nytimes.com/1987/01/02/nyregion/french-tourist-dies-of-injuries-after-a-mugging.html", title: "French tourist dies of injuries after a mugging",
    blurb: "A 71-year-old French tourist died early yesterday from head injuries suffered in a mugging as he walked to Times Square to view the New Year's Eve celebration. The victim, identified by the police as Jean Casse, left the Scarlatti restaurant, at 34 East 52d Street, near Madison Avenue, shortly before midnight in the company of his wife, Renee, and headed toward Times Square. According to the police, Mrs. Casse, 69, a retired doctor, tried to pull the mugger off her husband, but Mr. Casse fell to the ground as the mugger ripped through his pockets. Mr. Casse's head crashed into the sidewalk, and he fell into a coma shortly after his arrival at St. Luke's-Roosevelt Hospital. He died at about 10:30 A.M., of what a hospital spokesman said were &ldquo;massive intercranial injuries.&rdquo;",
    location: "34 East 52d Street", latlong: "40.7588766,-73.9743775", date: "1987" },
    { category: "envy", url_1: "http://www.nytimes.com/1987/11/09/nyregion/robbery-suspect-hurt-fleeing-in-subway-tunnel.html", title: "Man robs $95 from victim, then falls on 3rd rail in subway tunnel",
    blurb: "Ronald Ratliff, of 725 Stanley Avenue, in the Ozone Park section of Queens, was fleeing from the police after he and two other men allegedly robbed a 35-year-old man of $95 as he was coming out of the Holy Cross Church on West 42d Street at 11:30 A.M. The victim, Hugo Santana of Manhattan, who was with his wife and daughter, ran after the three men who fled into the IND subway station at 42d Street and Eighth Avenue, the police said. Mr. Ratliff, while attempting to jump onto a catwalk, fell onto the tracks, striking the third rail. He suffered burns of the head, right shoulder and left thigh and a broken shoulder. He was listed in critical condition at St. Vincent's Hospital. The police said he was charged with robbery, criminal trespass and criminal possession of stolen property.",
    location: "Holy Cross Church, 329 West 42nd Street", latlong: "40.758056,-73.990994", date: "1987" },
    { category: "envy", url_1: "http://query.nytimes.com/gst/abstract.html?res=F30D12F73F551A738DDDA80994D9405B828EF1D3", title: "Woman leaps from taxicab in Times Square, foils abduction and robbery by driver",
    blurb: "&ldquo;Mr. Mosher and I came out of the Empire Theater and hailed a brown and white taxi cab...I got into the taxicab while Mr. Mosher went into the National drug store, where he has left a prescription to be filled before going to the theater. The driver slammed the door when he saw a big man, weighing well over 200 pounds, approaching 42nd street, and leaped to his drivers seat. The large man got in the seat with him and commanded him to speed up. The driver disregarded my presence in the cab...fortunately, between 42nd and 43rd streets, a car ahead forced the can to stop. I jumped out unnoticed and ran back to the drug store. I am certain that the men intended to rob me of my fur and jewelry...I hope my experience will cause women to take precautions against similar outrages.&rdquo;",
    location: "Empire Theater, Broadway between 41st and 42nd sts", latlong: "40.7553845918663,-73.9864611625671", date: "1922" },
    { category: "envy", url_1: "http://www.nytimes.com/1992/07/24/nyregion/last-charges-dismissed-in-tourist-s-slaying.html", title: "Utah tourist stabbed to death defending family from muggers",
    blurb: "Utah tourist Brian Watkins is stabbed to death in the Seventh Avenue - 53rd Street station by a gang of youths. Watkins was visiting New York with his family to attend the US Open Tennis tournament in Queens, when he was killed defending his family from a gang of muggers. The killing marked a low point in the record murder year of 1990 and led to an increased police presence in New York. Seven of the eight defendants arrested in the case were all convicted of murder and were sentenced from 25 years to life in prison.",
    location: "Seventh Avenue - 53rd Street station", latlong: "40.7628286282639,-73.9816117286682", date: "1990" },
    { category: "envy", url_1: "http://www.nytimes.com/1990/08/27/nyregion/a-robbery-suspect-is-shot-in-times-square.html", title: "Robbery suspect shot in Times Square",
    blurb: "An armed-robbery suspect was shot and critically wounded and three other suspects arrested by police officers in a Times Square grocery. The incident occurred at 10:30 P.M. in the Almari Grocery - The police began pursuing the suspects when two officers on foot patrol were approached at the corner of 42d Street and Eighth Avenue by two people who said they had been robbed of their pocket money at gunpoint by four men. The victims pointed out the suspects to the police, who followed them to the grocery. The police said they recovered two fully loaded weapons.",
    location: "218 West 42nd Street", latlong: "40.7565194,-73.9882557", date: "1990" },
    { category: "envy", url_1: "http://articles.nydailynews.com/1996-10-03/news/18023147_1_subway-station-transit-cops-times-square", title: "Israeli tourist stabbed in the eye in subway mugging",
    blurb: "David Levy, 47, was partially blinded and suffered a loss of hearing when he was attacked by two men on the Seventh Ave. IRT in March 1991. The muggers robbed him of $5,000 in cash and other valuables. According to court papers, Levy had asked two transit cops for help after the men followed him into a subway station in Times Square. He said the officers told him to board the train, promising to protect him. But the cops did not intervene when the two men followed Levy on board. The muggers cornered Levy in an empty subway car, threw him to the floor, beat and kicked him and stabbed him in the eye. In a 4 to 1 vote, a state appeals court certified a lawsuit filed by the victim seeking $12.5 million in damages from the city and the Transit Authority.",
    location: "Times Sq subway: intersection of 42nd Street, Seventh Avenue, and Broadway", latlong: "40.7546694003754,-73.9867186546326", date: "1991" },
    { category: "gluttony", url_1: "http://en.wikipedia.org/wiki/International_Federation_of_Competitive_Eating", url_2: "http://www.ifoce.com/about.php", title: "The International Federation of Competitive Eating HQ in Times Square",
    blurb: "The International Federation of Competitive Eating, Inc. (IFOCE) is an organization that supervises and regulates eating contests across the globe, acting as a central resource for the sport. Top events include the Nathan's Hot Dog Eating Contest, La Costena &ldquo;Feel the Heat&rdquo; Jalapeno Eating Challenge, and the Krystal Square Off World Hamburger Eating Championship. The IFOCE was founded in 1997 by brothers George and Richard Shea. The IFOCE maintains principal offices in New York City and operates in the United States, Japan, the United Kingdom, Germany, Canada and Thailand. The Discovery Channel, Travel Channel, the TV Food Network and the UK’s Channel Four have also aired one-hour documentaries on eating and the IFOCE and Fox Television aired a two-hour IFOCE championship.<br/><br />The IFOCE maintains a ranking system for competitions it has sanctioned. IFOCE safety measures ensure that all sanctioned matches occur in a controlled environment under the supervision of a licensed emergency medical technician and that only individuals over the age of eighteen compete.",
    location: "International Federation of Competitive Eating 18 East 41st. Street, 15th Floor", latlong: "40.752449,-73.980504", date: "1997" },
    { category: "gluttony", url_1: "http://www.ifoce.com/news.php?action=detail&sn=105", url_2: "http://www.abcsupersign.com/", title: "ESPN’s inaugural telecast of the 2004 Nathan’s Hot Dog Eating Contest, simulcast from the Times Square ABC SuperSign",
    blurb: "ESPN’s inaugural telecast of the 2004 Nathan’s Hot Dog Eating Contest, simulcast from the Times Square ABC SuperSign - ESPN’s telecast featured a 40-minute pre-game segment highlighting the history of the event and outlining the rules of the competition, leading in to the 12-minute, all-you-can-eat contest. The event showcased 20 eating competitors (13 from the United States, two from Japan, and one each from England, New Zealand, Germany, and Canada), including Japan’s Takeru Kobayashi. The ABC SuperSign is the 3,685-square foot electronic icon in Times Square known to millions worldwide for its signature wavy LED ribbons, eye-catching curved ticker and daily exposure on ABC’s Good Morning America. ",
    location: "1500 Broadway @ 44th Street", latlong: "40.7564745,-73.9859448", date: "2004" },
    { category: "gluttony", url_1: "http://en.wikipedia.org/wiki/Weight_gain", title: "64% of the US adult population is considered either overweight or obese, and this percentage has increased over the last four decades",
    blurb: "Being fat is a common condition, especially where food supplies are plentiful and lifestyles are sedentary. As much as 64% of the United States adult population is considered either overweight or obese, and this percentage has increased over the last four decades. In centuries past, a degree of plumpness has been seen as indicative of personal or family prosperity: &ldquo;Calories were scarce, physical labor was hard, and most people were as lean as greyhounds.&rdquo; In particular, a married woman who was thin was pitied, as her shape showed that her husband could not afford to feed her properly; conversely, having a fat wife was a status symbol: there was plenty to eat, and she did not need to work hard. Only in the early 20th Century did fatness lose this appeal. The connection of fatness with financial well-being persists today in some less-developed countries. Though excess weight has for some time been seen in contemporary Western society as &ldquo;unacceptable&rdquo;, it is becoming more socially acceptable as more and more people become overweight and obese.",
    location: "Broadway Plaza from 47th Street to 42nd Street", latlong: "40.7591249992889,-73.9847995340824", date: "1900s" },
    { category: "gluttony", url_1: "http://en.wikipedia.org/wiki/Weight_gain", title: "Obesity among women residing in the U.S. has become more socially acceptable, likely in part because more than one-third of women ages 20 and older are obese",
    blurb: "Obesity among women residing in the U.S. has become more socially acceptable, likely in part because more than one-third of women ages 20 and older are obese, according to a study published in the July issue of Economic Inquiry, the Washington Times reports. The researchers found that the average weight of women between ages 30 and 60 has increased by 20 pounds, or 14%, since 1976. Among women who weigh 300 pounds or more, the increase was 18%, the researchers found. The researchers also found that self-image has changed and that obesity has become more socially acceptable in the United States. According to the study, the average woman weighed 147 pounds in 1994 but stated that she wanted to weigh 132 pounds. By 2002, the average women weighed 153 pounds but said she wanted to be 135 pounds, the study found. &ldquo;The fact that even the desired weight of women has increased suggests there is less social pressure to lose weight,&rdquo; the researchers noted.",
    location: "Broadway Plaza from 47th Street to 42nd Street", latlong: "40.7585114324905,-73.9852809906006", date: "2002" },
    { category: "gluttony", url_1: "http://amy-sillup.suite101.com/fad-diets-a193125", title: "Around 1900, United States citizens became obsessed with weight control",
    blurb: "Around 1900, United States citizens became obsessed with weight control; since then, Americans have wasted countless hours and dollars in pursuit of diet fads and frauds. By 1961, 40% of Americans were buying and consuming diet products. By 1979, Weight Watchers was pulling in almost $40 million in yearly profits. By 1990, dieting was a $33 million dollar business. Overweight people were shamed in the media, often presented as unpatriotic or immoral in their profligacy. In the 21st century, it has become virtually impossible to sort out all the fad diets and exercise programs. Americans have chased after the Rice Diet, the Atkins Plan, low-carb, low fat, have ranged from the Mediterranean to Sonoma to Beverly Hills in their quest for the perfect program. They’ve quaffed gallons of cabbage soup and Slim-Fast, and even valiantly (and briefly) attempted to “eat like the French,” whatever that meant. Realistically, each individual has to eat the same amount of calories as he expends in order to reach or remain at his ideal weight; he should also engage in some type of enjoyable physical activity. Barring a medical condition, such a program will result in success. However, if history is any guide, Americans find sensible weight loss and maintenance methods too boring and slow. Thus the U.S. will continue to fall for the latest fad with great enthusiasm, while carefully keeping an eye peeled for the next overrated nostrum on the horizon. Even in a field ostensibly concerned with deprivation, the U.S. simply loves excess.",
    location: "Broadway Plaza from 47th Street to 42nd Street", latlong: "40.7582432491973,-73.9855679869652", date: "1900" },
    { category: "gluttony", url_1: "http://en.wikipedia.org/wiki/Texas_Guinan", title: "Prohibition bans alcohol, Americans find new ways to overindulge at the 300 Club",
    blurb: "Upon the introduction of Prohibition, Texas Guinan opened a speakeasy called the 300 Club at 151 W. 54th Street in New York City. The club became famous for its troupe of forty scantily-clad fan dancers and for Guinan's distinctive aplomb, which made her a celebrity. Arrested several times for serving alcohol and providing entertainment, she always claimed that the patrons had brought the liquor in with them, and the club was so small that the girls had to dance so close to the customers. Guinan maintained that she had never sold an alcoholic drink in her life. Ruby Keeler and George Raft were discovered as dancers at the club by Broadway and Hollywood talent scouts. Walter Winchell credited Guinan with opening the insider Broadway scene and cafe society to him when he was starting as a gossip columnist. Guinan capitalized on her notoriety, earning $700,000 in ten months in 1926, while her clubs were routinely being raided by the police. She traditionally greeted her patrons with &ldquo;Hello, suckers!&rdquo;",
    location: "151 W. 54th Street", latlong: "40.7633541,-73.9807722", date: "1920" },
    { category: "greed", url_1: "http://www.nytimes.com/2000/08/02/dining/restaurants-where-to-take-your-gambling-spirit.html", url_2: "http://en.wikipedia.org/wiki/Hotel_Metropole_%28New_York%29", title: "Gambling House operator murdered by police detective for kickbacks",
    blurb: "Six men pulled up outside the Metropole Hotel in Times Square and gunned down a gambling-house operator named Herman Rosenthal. It was a brazen murder, and the police moved quickly. They discovered, to their embarrassment, that the hit had been ordered by one of their own, Lt. Charles Becker, who wanted more than the 50 percent of Rosenthal's proceeds that he had been getting. Jack Rose, a rival of Rosenthal's and the man who hired the getaway car, provided the evidence that sent Lieutenant Becker to the chair. In addition to immunity, Rose got a drink named after him, a witty blend of applejack and lemon juice, colored with a splash of grenadine.",
    location: "Metropole Hotel, 147 West 43rd Street ", latlong: "40.7563551,-73.9854831", date: "1912" },
    { category: "greed", title: "Mob boss Paul Castellano is shot dead in a gangland execution on E. 46th Street",
    blurb: "In March 1984, Castellano was indicted by Rudolph Giuliani, the chief federal prosecutor for Manhattan, on Racketeer Influenced and Corrupt Organizations charges. The indictment alleged that the crew committed 25 murders (which included 2 murdered witnesses). In early 1985, he was one of many Mafia bosses arrested on charges of racketeering, which was to result in the Mafia Commission Trial. Castellano was released on $3 million bail. On December 2, 1985, Aniello &ldquo;Neil&rdquo; Dellacroce died of lung cancer. Castellano then made two major mistakes. First, he did not attend Dellacroce's funeral - which was viewed as highly disrespectful by the Dellacroce/Gotti loyalists. Second, Castellano then named his bodyguard, Tommy Bilotti, as the new underboss. Although Bilotti was a loyal mobster, he was also a brutish loanshark with little of the diplomatic skill required to hold such a high rank within the organization. The final nail in his coffin was put in place when he announced to the family that he was breaking up Gotti's crew and reassigning them. Within two weeks of Dellacroce's death, on December 16, Castellano and Bilotti were shot to death outside Sparks Steak House in Manhattan on the orders of John Gotti. They had been lured there supposedly to a meeting with Gotti in order to iron out their differences.",
    location: "Spark's Steakhouse, 210 east 46th st", latlong: "40.753239,-73.972149", date: "1985" },
    { category: "greed", url_1: "http://www.archives.gov/exhibits/new_deal_for_the_arts/images/activist_arts/friday_the_13th.html", url_2: "http://www.archives.gov/exhibits/new_deal_for_the_arts/activist_arts1.html", title: "WPA artists protest for their rights against personnel and wage cuts",
    blurb: "In the highly charged political atmosphere of the Great Depression, left-wing project employees not only painted, acted, and wrote, they demonstrated, published newspapers, and led sit-in strikes to protest WPA personnel and wage cuts. Artists from many different leftist points of view also embraced causes such as industrial unionism, civil rights for black Americans, and support for the anti-fascists in the Spanish Civil War. Such political activity was common in the 1930s, and though the number of actual Communist Party members was small, it helped lead to a backlash from politicians and others who claimed the projects were filled with Communists.",
    location: "108 West 43rd Street", latlong: "40.7560823,-73.9850093", date: "1937" },
    { category: "greed", url_1: "http://www.ny1.com/content/top_stories/47649/guns-stolen-from-museum-exhibit-at-times-square", url_2: "http://www.narconon-news.org/drug_prevention_rehab_news/DEA_press_release_oct_2004.htm", title: "Inoperable guns stolen from a DEA Museum exhibit in Times Square",
    blurb: "The Drug Enforcement Administration is reviewing security at its museum in Times Square, after three large inoperable guns were stolen from an exhibit that opened in 2004.  Employees at the DEA museum noticed the guns were missing on Wednesday. The weapons, a 45-caliber Ruger and two 40-caliber Sig Sauer guns were part of an exhibition titled &ldquo;Target America: Drug Traffickers, Terrorists and You.&rdquo;  All three guns were screwed down in place with metal bars stretched across them. A DEA spokesman says the guns probably cannot be restored to fire live ammunition.",
    location: "DEA Museum and Visitors Center, 1 Times Square", latlong: "40.7563110784949,-73.9863914251328", date: "2004" },
    { category: "greed", url_1: "http://en.wikipedia.org/wiki/Guys_and_Dolls#Original_productions", url_2: "http://en.wikipedia.org/wiki/Guys_and_Dolls_(film)", title: "Guys and Dolls, a musical about a Times Square premiered on Broadway",
    blurb: "The musical Guys and Dolls, based on the story Arnold Rothstein, the Times Square gambling kingpin who became the inspiration for Nathan Detroit, premiered on Broadway at the 46th Street Theatre on November 24, 1950. Although there are detail differences between the stage and movie versions (which stared Fred Astaire, and Marlon Brando, released in 1955), the plot is essentially based on the activities of New York petty criminals and professional gamblers in the late 1940s. The original musical production was directed by George S. Kaufman, and starred Robert Alda, Sam Levene, Isabel Bigley, and Vivian Blaine. The musical ran for 1,200 performances, winning five 1951 Tony Awards, including the award for Best Musical. Decca Records issued the original cast recording on 78 rpm records, which was later expanded and re-issued on LP, and then transferred to CD in the 1980s.", 
    location: "226 W 46th Street", latlong: "40.759034,-73.986747", date: "1950" },
    { category: "greed", url_1: "http://en.wikipedia.org/wiki/Larry_Fay", url_2: "http://www.crimemagazine.com/three-thin-dimes-demise-larry-fay", title: "Larry Fay, and his nightclub El Fey, reaped in the cash while Prohibition raged",
    blurb: "Larry Fay (1888 – January 1, 1933) was one of the early rumrunners of the Prohibition Era in New York City. He made a half a million dollars bringing whiskey into New York from Canada. Fay took his bootlegging profits and put them into his taxi cab company. His cabs were designed to be as flashy as he was. They had lots of nickel trimming, lights on both the top and sides, and musical horns. Fay’s drivers took many inebriated customers to &ldquo;clip joints&rdquo; that sprang up when prohibition started. Clip joints were elaborately concealed speakeasies where the drunken patrons were rendered unconscious by more liquor, or if necessary, drugs. They were then relieved of their money and driven a short distance from the area and deposited in the gutter. He later opened a nightclub, the El Fey, on West 47th Street in Manhattan in 1924, featuring Texas Guinan as the emcee and a floorshow produced by Nils Granlund. Fay, who had a record of forty-nine arrests but no felony convictions, was involved in several enterprises in the ensuing years, and was said to have amassed and lost a fortune. He was made a partner of the Casa Blanca Club, where he was shot four times after a 1932 New Year's Eve celebration by the club's doorman who had just learned his pay was being reduced by Fay to accommodate a new employee. He died the next day. On December 15, 1960, The Untouchables (1959 TV series) during its second season did The Larry Fay Story. This episode (the 37th for the series) dealt with Larry Fay's activities in the New York City milk price-fixing case. Also, Fay's life served as the basis for James Cagney's character, Eddie Bartlett, in the 1939 gangster film, The Roaring Twenties.",
    location: "West 47th St and Broadway", latlong: "40.7598299846116,-73.9860427379608", date: "1924" },
    { category: "greed", url_1: "http://en.wikipedia.org/wiki/National_Debt_Clock", title: "The National Debt clock",
    blurb: "The National Debt Clock is a billboard-sized running total dot-matrix display which constantly updates to show the current United States gross national debt and each American family's share of the debt. The idea for the clock came from New York real estate developer Seymour Durst, who wanted to highlight the rising national debt. In 1989, he sponsored the installation of the first clock - It was mounted a block from Times Square, on a Durst building at Sixth Avenue near 42nd Street, facing the north side of 42nd Street and Bryant Park across the intersection. At the time, the national debt remained under $3 trillion but was rising. The clock was temporarily switched off from 2000 to 2002 due to the debt actually falling during that period. In 2004, the original clock was dismantled and replaced by the current clock at the new location one block away. In 2008, the U.S. national debt exceeded $10 trillion for the first time, leading to press reports that the clock had run out of digits. According to Douglas Durst, his father had been toying with the basic idea of drawing attention to the growing national debt since at least 1980, when during the holiday season he sent cards that said &ldquo;Happy New Year. Your share of the national debt is $35,000&rdquo; to senators and congressmen. In the early eighties, when Durst first developed the idea of a constantly updated clock, the technology required to implement the project was not yet available.",
    location: "Sixth Avenue near 42nd Street", latlong: "40.7548522625683,-73.9841276407242", date: "1989" },
    { category: "lust", url_1: "http://politicalticker.blogs.cnn.com/2011/04/13/clinton-remembers-old-times-square-crime-hookers/", title: "Bill Clinton remembers old Times Square: crime, hookers",
    blurb: "&ldquo;When I was 18 years-old in November of 1964, a freshman at Georgetown, I first went to Times Square. I bought a steak at Tad's Steakhouse. I heard a guy ream his mother out, poor working woman, because she'd given him a hi-fi instead of a stereo speaker. I remember everything about it. I saw a hooker approach a man in a gray flannel suit. Pretty heavy stuff for a guy from Arkansas,&rdquo; Clinton said.",
    location: "Tad's Steakhouse, 152 W 34th St", latlong: "40.7506443,-73.9900419", date: "1964" },
    { category: "lust", url_1: "http://www.timessquare.com/NYC__/Times_Square_History/Sex_and_the_Square/", title: "&ldquo;Soubrette Row&rdquo;: French prostitutes were notorious for having no limits",
    blurb: "In 1880 it was estimated that a dozen brothels each lined West 39th and 40th streets alone. West 39th was such a well-known place for French brothels it was dubbed &ldquo;Soubrette Row&rdquo; by patrons. French prostitutes were notorious for having no limits: they would do anything and everything for the right price. On weekend nights young men lined up outside brownstones in the district while streetwalkers made use of Broadway and 42nd street. Ministers of nearby churches complained that after Sunday evening services 'harlots' solicited men leaving the services. ",
    location: "Broadway and 39th st", latlong: "40.7535315798747,-73.9871263504028", date: "1880" },
    { category: "lust", url_1: "http://www.timessquare.com/NYC__/Times_Square_History/Sex_and_the_Square/", url_2: "http://en.wikipedia.org/wiki/Longacre_Square", title: "Women often worked simultaneously as chorus girls and prostitutes to pay the rent",
    blurb: "What once was respectable became lowdown and squalid. The legion of family brownstones erected by optimistic developers in the former Longacre Square turned into saloons and brothels. Times Square, with its burlesque halls, vaudeville stages and dime houses, began to acquire a reputation for licentiousness. Two infamous madams, May Livingston and Ann Grey, ran half a dozen houses of ill repute between them. While brothels opened and closed with regularity, their women often worked simultaneously as chorus girls and prostitutes to pay the rent.",
    location: "Times Square District", latlong: "40.7585215909273,-73.9888429641724", date: "1880" },
    { category: "lust", url_1: "http://cityroom.blogs.nytimes.com/2008/06/26/times-squares-seedier-side-returns-have-a-peep/", title: "Recreating massage parlours from the 1970's",
    blurb: "What if you need the sex shops and porn shows of 1970s Times Square for a movie shoot? You recreate it. That's what a movie crew recreated the old 42nd Street on today’s West 38th Street just off of Eighth Avenue, for the film “All Good Things” starring Kirsten Dunst and Ryan Gosling, set for release in 2009. Thus, a tourist shop owned by Pakistani immigrants was converted into a peep show (eXXXotic!), the Japanese curry shop became a massage harem with “Oriental” girls, the Chinese bakery (not “Oriental bakery”) became a Times Square coffee shop (much to the dismay of Midtown diners) and the Manhattan Hotel became the Luxor Hotel.",
    location: "38th st and 8th ave", latlong: "40.7547181636761,-73.9915680885315", date: "1970s" },
    { category: "lust", url_1: "http://www.nytimes.com/interactive/2011/01/26/nyregion/gentleman.html", title: "From The Gentleman’s Directory, 1870",
    blurb: "Beware the many “well-dressed and comely females ... unattended by companions of the other sex,” who can be seen along the boulevard. For these are “Nymphes de Pave” — streetwalkers — who have “robbed many an unsuspecting stranger of his all.”",
    location: "Broadway and 31st street", latlong: "40.7474845499371,-73.9883494377136", date: "1870" },
    { category: "lust", url_1: "http://forgotten-ny.com/2008/09/old-42-remnants-of-the-old-deuce-manhattan/", url_2: "http://en.wikipedia.org/wiki/New_Victory_Theatre", title: "Burlesque ruled at The Republic, then an XXX rated filmhouse",
    blurb: "The New Victory Theatre was built as The Republic in 1899 by Oscar Hammerstein I (from 1902-1910 it was called The Belasco). It was home to Abe, Billy, Herbert and Morton Minsky’s burlesque shows between 1912 and 1937. The show was a launching pad for comics like Phil Silvers, Joey Faye and Red Skelton, and of course famed strippers Gypsy Rose Lee and Ann Corio. Eventually the Fiorello LaGuardia administration forced out the Minskys. The house was raided often, but one such incident inspired a 1968 motion picture starring Jason Robards, Elliott Gould and Britt Ekland. When the old Republic was restored as the New Victory in 1995, one of the first comebacks on West 42nd, it was decided to devote it exclusively to children’s and family-friendly programming.",
    location: "The New Victory Theater, 209 West 42nd Street, between 7th and 8th Avenues", latlong: "40.7563426,-73.9876344", date: "1995" },
    { category: "lust", url_1: "http://forgotten-ny.com/2008/09/old-42-remnants-of-the-old-deuce-manhattan/", url_2: "http://www.nytimes.com/2004/06/13/nyregion/times-square-at-100-up-in-the-old-hotel.html", title: "The last flophouse in Times Square: The Elk Hotel",
    blurb: "The Times’ Steven Kurutz dropped in in 2004: A rickety old staircase leads from the street up to a locked glass door, where guests are buzzed into a tiny lobby. To the right and lining the first floor are the ”short stay” rooms, which rent for $25 for two hours; to the left and up a flight reside longer-term guests.Moving along the hallways, painted a dizzying aqua, and peeking into the rooms, one can almost imagine the figures that once ran rampant in old Times Square: teenage runaways, ex-cons, junkies and hustlers, lonely drunks, all the lost souls that nested here for a time. The hotel has lately been popular with Mexican workers, and this day two laborers, their jeans and boots covered in dust, sat on the lobby stairwell eating rice and beans. Men followed by scantily clad women bounded up the stairs most of the day.",
    location: "The Elk Hotel, SE corner of West 42nd and 9th Avenue", latlong: "40.7582940415707,-73.9926034212112", date: "2004" },
    { category: "lust", url_1: "http://www.nytimes.com/2010/12/06/nyregion/06peep.html", title: "Last peepshow palace Peep-O-Rama closes.",
    blurb: "When it was finally shuttered eight years ago, Peep-O-Rama achieved a public cachet that it had never gained in its five decades: the garish pornography emporium was the last peep show palace on “the Deuce.” While its closing was celebrated as heralding the rebirth of Times Square, it also generated a few nostalgic lamentations about the passing of a more adventurous, if decidedly dangerous and seedy, era. Its newly restored orange neon sign — donated by the Durst Organization, Peep-O-Rama’s former landlord, and restored by Let There Be Neon — will greet sightseers in an ingenious refurbishment of the visitors center run by the Times Square Alliance at 1560 Broadway, between West 46th and 47th Streets.",
    location: "1560 Broadway, between West 46th and 47th Streets.", latlong: "40.7587464,-73.9852954", date: "2002" },
    { category: "pride", url_1: "http://www.nycparamount.com/paramountbar.html", title: "The place to go to &ldquo;see and be seen&rdquo; since 1928",
    blurb: "This modern legendary New York City bar has been the place where in-the-know New Yorkers go to “see and be seen”—and to drink high-quality specialty beverages since 1928. This New York City bar has played host to celebrity parties, and has even been known to serve a few celebrities who were trying to blend in with the crowds.",
    location: "Paramount Hotel, 235 West 46th St", latlong: "40.7594216,-73.9869079", date: "1928" },
    { category: "pride", url_1: "http://www.nyctourist.com/times-square-history.php", title: "Times Square acquired its name in 1904 when The New York Times moved the newspaper's HQ uptown",
    blurb: "Times Square acquired its name in 1904 when Albert Ochs, publisher of The New York Times, moved the newspaper's headquarters to a new skyscraper on what was then known as Longacre Square. The name stuck, even after The New York Times moved across Broadway in 1913, and it is now known worldwide as a symbol of the American spirit. Longacre Square started with a few brownstones built by a developer who saw potential for a new &ldquo;uptown&rdquo; neighborhood. Following the area's development, people moved to the square in droves, and with them came brothels, pickpockets, and streetwalkers. Soon, in a foreshadowing of its later fate, the area turned into a veritable red-light district. In 1895, Longacre Square had a new tenant, Oscar Hammerstein I, who developed a large entertainment complex in the hopes of rekindling an interest in opera. This complex, called the Olympia, occupied a full block on 42nd Street and featured three theaters. During this time, many new theaters opened on the Great White Way, so named for Broadway's famous light show. The vaudeville circuit found success along with legitimate theater.",
    location: "Times Square Building, One Times Square", latlong: "40.7564979996706,-73.9864128828049", date: "1904" },
    { category: "pride", url_1: "http://www.timessquarenyc.org/nye/nye_ball.html", url_2: "http://www.nyctourist.com/new-years-eve-times-square-celebration", title: "All eyes are on Times Square each New Years Eve, to watch the ball drop",
    blurb: "Revelers began celebrating New Year's Eve in Times Square as early as 1904, but it was in 1907 that the New Year's Eve Ball made its maiden descent from the flagpole atop One Times Square.<br /><br />As part of the 1907-1908 festivities, waiters in the fabled &ldquo;lobster palaces&rdquo; and other deluxe eateries in hotels surrounding Times Square were supplied with battery-powered top hats emblazoned with the numbers &ldquo;1908&rdquo; fashioned of tiny light bulbs. At the stroke of midnight, they all &ldquo;flipped their lids&rdquo; and the year on their foreheads lit up in conjunction with the numbers &ldquo;1908&rdquo; on the parapet of the Times Tower lighting up to signal the arrival of the new year.<br /><br />The Ball has been lowered every year since 1907, with the exceptions of 1942 and 1943, when the ceremony was suspended due to the wartime &ldquo;dimout&rdquo; of lights in New York City. Nevertheless, the crowds still gathered in Times Square in those years and greeted the New Year with a minute of silence followed by the ringing of chimes from sound trucks parked at the base of the tower - a harkening-back to the earlier celebrations at Trinity Church, where crowds would gather to &ldquo;ring out the old, ring in the new.&rdquo; The actual notion of a ball &ldquo;dropping&rdquo; to signal the passage of time dates back long before New Year's Eve was ever celebrated in Times Square. The first &ldquo;time-ball&rdquo; was installed atop England's Royal Observatory at Greenwich in 1833. This ball would drop at one o'clock every afternoon, allowing the captains of nearby ships to precisely set their chronometers (a vital navigational instrument). In 1972, Dick Clark began hosting the half-hour special Dick Clark's New Year's Rockin' Eve.",
    location: "One Times Square", latlong: "40.7560550769017,-73.9865201711655", date: "1904" },
    { category: "pride", url_1: "http://timessquare.com/NYC__/Times_Square_History/Mysterious_Noises_on_46th_Street/", title: "You're not crazy, there really are mysterious noises on 46th Street",
    blurb: "In the midst of Times Square, the bustling, light filled, people-packed, center of New York City, there is a secret. As many as one thousand people in an hour cross the pedestrian island that runs between 45th and 46th Street where Broadway and 7th Avenue intersect, not noticing that there is anything that differentiates this island from all the others in Manhattan. However those people with particularly open ears, or those who happen to be walking slightly below the average New York pace, may notice a mysterious humming noise, rather like the clanking of a distant machine. Although no plaque can be found, no explanatory text to accompany this unique experience, it is, in fact, a work of art, entitled Times Square, and its artist is Max Neuhaus. The work was originally installed at the same site from 1977-1992, at which point Neuhaus dismantled it because he had to return to Europe and the piece required constant monitoring. However, Times Square was missed, and during 2001 and 2002, the Times Square Street Business Improvement District (BID), Christine Burgin, the MTA Arts for Transit, and the Dia Art Foundation collaborated to reinstate Neuhaus's project. The block of sound returned to 46th Street on 22 May 2002, where it has remained for the public to experience twenty-four hours a day, seven days a week. While standing inside Neuhaus's project, the sound seems most intense at the level right above your head, enhancing the illusion that the noises have no agent. Neuhaus says the sound must be made to be &ldquo;almost plausible,&rdquo; so that when people can't find any immediate cause, they think it comes from the subway. In reality, they are correct that the sound originates in the subway chamber below. The North side of the pedestrian island, at 46th Street, is covered by a large subway grating which spans an area of the Times Square 42nd Street station where several subway tunnels intersect. The block of sound that seems to hover above the island is created from resonances that are already present below the ground due to this unusual tunnel junction. Neuhaus listened closely to these sounds, and he built a machine that would amplify and enhance the resonances so they could be heard above ground. He then spent months creating the block of sound that we now experience. Neuhaus did this without the aid of computer or electronic music, and the block of sound is built entirely from already existing resonances. For this reason, Neuhaus speaks of &ldquo;building&rdquo; rather than &ldquo;composing&rdquo; his sound.",
    location: "Times Square Pedestrian Island", latlong: "40.7588466600855,-73.9850878715515", date: "1977" },
    { category: "pride", url_1: "http://gonyc.about.com/od/photogalleries/ss/times_square_5.htm", title: "Statue of George M. Cohen, theater figure",
    blurb: "George M. Cohan was a famous figure in the New York City theater scene just after the turn of the century. Little Johnny Jones, his first big Broadway hit introduced his songs &ldquo;Give My Regards To Broadway&rdquo; and &ldquo;The Yankee Doodle Boy&rdquo;. His statue was erected in the 1960s in recognition of musical contributions to the war effort through his songs &ldquo;You're a Grand Old Flag&rdquo; and &ldquo;Over There.&rdquo;",
    location: "Duffy Square", latlong: "40.759194075991,-73.9849430322647", date: "1960's" },
    { category: "pride", url_1: "http://en.wikipedia.org/wiki/George_Selden_(author)", title: "George Selden received the Newbery Honor Book Award, and Lewis Carroll Shelf Award for his book, The Cricket in Times Square",
    blurb: "George Selden Thompson (May 14, 1929 – December 5, 1989) was an American author, who wrote under the pseudonym George Selden. He is best known for his 1961 book The Cricket in Times Square, which received a Lewis Carroll Shelf Award in 1963 and a Newbery Honor. Selden is best known as the author of several books about the character Chester Cricket and his friends. The first book, The Cricket in Times Square, was a Newbery Honor Book in 1961. Selden explained the inspiration for that book as follows: One night I was coming home on the subway, and I did hear a cricket chirp in the Time Square subway station. The story formed in my mind within minutes. An author is very thankful for minutes like those, although they happen all too infrequently.",
    location: "Times Square subway station: intersection of 42nd Street, Seventh Avenue, and Broadway", latlong: "40.7549132165208,-73.9874911308289", date: "1961" },
    { category: "pride", url_1: "http://www.citysightsny.com/page.php?id=94", title: "Irving Berlin, Fred Astaire, and Charlie Chaplin were closely associated with Times Square",
    blurb: "As New York City's growth continued, Times Square quickly grew as a cultural hub full of theaters, music halls, and upscale hotels. Times Square quickly became New York's agora, a place to gather both to await great tidings and to celebrate them, whether a World Series or a presidential election —James Traub, The Devil's Playground: A Century of Pleasure and Profit in Times Square. Celebrities such as Irving Berlin, Fred Astaire, and Charlie Chaplin were closely associated with Times Square in the 1910s and 1920s.",
    location: "Times Square District", latlong: "40.7570343792565,-73.9859354496002", date: "1910s" },
    { category: "sloth", url_1: "http://www.npr.org/2011/03/07/134002013/ending-homelessness-a-model-that-just-might-work", url_2: "http://www.commonground.org/", title: "Anti-sloth: helping the homeless",
    blurb: "&ldquo;In the early '80s, I lived right next-door to the Times Square Hotel,&rdquo; she says. &ldquo;It was back in the day when Times Square was Times Square, as we say — kind of a crazy neighborhood to say the least.&rdquo; The area was known mostly for peep shows and prostitutes. It was long before anyone dreamed that Times Square would become a family destination.<br /><br />Rosanne Haggerty worked with the homeless at the time, and was upset to find out that the hotel was about to shut down. &ldquo;It was the largest single-room occupancy hotel in New York City,&rdquo; she says. &ldquo;The building was practically on the verge of being condemned. It had 1,700 serious building code violations.&rdquo;<br /><br />Trash, mildew and crack vials were everywhere. But Haggerty, then 29, saw the potential. She says she thought it made a lot of sense to fix the building up so all of the homeless people outside would have somewhere to live. And she thought it would be good to provide services, like health care and job training, so people would be more likely to stay off the streets.  It was 1990, and city leaders were eager to clean up the Times Square area and to deal with New York's growing homeless problem. The federal government also had money to help. So Haggerty founded Common Ground and got to work.",
    location: "505 Eighth Avenue", latlong: "40.7530121,-73.9928657", date: "1990" },
    { category: "sloth", url_1: "http://books.google.com/books?id=WcDpqG5BP1EC&pg=PA30&lpg=PA30&dq=vagrants+times+square&source=bl&ots=H4W7fYSeHJ&sig=112UcQw1kn74aw-ajwmDWZhLKVI&hl=en&ei=H4yGTq2fAczK0AHR7rXsDw&sa=X&oi=book_result&ct=result&resnum=5&ved=0CDMQ6AEwBA#v=onepage&q=vagrants%20times%20square&f=false", title: "Homelessness ignored as social problem in Times Square until 1978",
    blurb: "In 1977 New York Times coverage (of homelessness) was restricted to crimes committed by &ldquo;vagrants&rdquo; with one exception - a human interest story about the lives of steam-tunnel dwellers beneath the city. In 1978 as well, most news stories concerned a rash of murders of &ldquo;skid row bums&rdquo; (seventeen separate articles in 1978 reported on this theme). In November of that year, homelessness was presented as a social problem in the Times. Times Square was reported to have a problem with &ldquo;sleepy winos&rdquo; and &ldquo;aggressive street corner drinkers.&rdquo; This was because, the paper reported, these street dwellers had judged the Times Square area to be safer than the Bowery, where a rash of &ldquo;muggers, drug addicts, the conversion of flophouses to loft apartments, and the influx of mental patients&rdquo; had made the area unlivable (NYT, November 14, 1978). - From the book Seasons such as these: how homelessness took shape in America by Cynthia J. Bogard",
    location: "Times Square District", latlong: "40.7576520231157,-73.985720872879", date: "1978" },
    { category: "sloth", url_1: "http://books.google.com/books?id=7BP6qjN8UGcC&pg=PA19&dq=times+square+vagrants&hl=en&ei=S_-GTujBM4Pi0QH-g-QL&sa=X&oi=book_result&ct=result&resnum=7&ved=0CEoQ6AEwBg#v=onepage&q=times%20square%20vagrants&f=false", title: "It's true: the police cannot arrest people simply because they are standing around",
    blurb: "Loitering presented the police with a special problem - the &ldquo;indescernible mix of those engaged in, or about to engage in, illegal activities and those the Draft Environmental Impact Statement (DEIS) described as just &ldquo;hanging around&rdquo; to experience the excitement of 42nd Street.&rdquo; The street population of the Deuce was an &ldquo;outdoor circus of people&rdquo; made up of several groups: the regulars &ldquo;in the life&rdquo; at their hangouts, on their &ldquo;strolls,&rdquo; or on their &ldquo;hustles&rdquo;; the winos, vagrants, derelicts, and other street people ambling about or lying in doorways in one state or another, the pedestrians on their way somewhere, movie goers, and the tourists, joined by street-preaching revivalists, peddlers, and errant window shoppers. As the DEIS went on  to explain: There are, after all, no laws in our society which foreclose standing on public sidewalks to watch those passing by, but on the contrary, the ability to assemble freely is constitutionally protected. The police cannot arrest people simply because they are standing around - and this is a good deal of what takes place on 42nd Street. Yet it is also in [this] context ... that the illegal activities function and are able to function. The crowds provide the market and the screen for the hustlers and pushers - the market in the sense of potential customers and the screen in the sense that those hanging around are often indistinguishable from criminals. From the book Times Square Roulette: Remaking the City Icon by Lynne B. Sagalyn",
    location: "Times Square District", latlong: "40.7580339842095,-73.9853882789612", date: "1978" },
    { category: "sloth", url_1: "http://www.fitlink.com/location?location=11879", url_2: "http://www.modells.com/corp/index.jsp;jsessionid=wG6GTHCTkxXyTbkbwJTlQcCS79vfhmMlnnCZx15wnp1SzyQGnrcT!-248982156?clickid=botnav_about_txt", title: "The anti-sloth: the oldest family owned and operated sporting goods and athletic store in the country",
    blurb: "Modell's Sporting Goods is the nation's oldest, family-owned and operated, retailer of sporting goods, sporting apparel, menswear and brand name athletic footwear. Modells.com currently offers a large collection of products from top name brands in the sporting goods and apparel business. Modell's, founded in 1889 by Morris A. Modell, had its first store located on Cortlandt Street in lower Manhattan. Four generations of the Modell family have developed the family business into a chain of stores located in the northeast.",
    location: "234 W 42nd St", latlong: "40.756392,-73.988307", date: "1889" },
    { category: "sloth", url_1: "http://ezinearticles.com/?Heisman-Trophy-History&id=6321125", title: "The anti-sloth: The Heisman trophy now presented in Times Square",
    blurb: "Named in honor of John Heisman, the Heisman Memorial Trophy Award - less formally known as the Heisman or the Heisman Trophy - is presented by the Heisman Trophy Trust each year in early December, before the start of the post-season bowl games, to the college football player regarded as that past season's most outstanding player in the nation. Created in 1935, it is one of the oldest college football awards, has been presented a total of 75 times in its history so far, and is considered to be one of the highest individual college football honors.<br /><br />Prior to the September 11th attacks in 2001, the Heisman Trophy Awards ceremony had taken place at the Downtown Athletic Club in New York City. However, after the southern Manhattan facility was damaged in the terrorist attacks, the New York Marriott Marquis in Times Square became the venue for that year. The following year, in 2002, the Downtown Athletic Club declared bankruptcy, so Yale Club became the venue that year and the next. In 2004, it took place at the Hilton New York. Since 2005, the award has been presented at the Nokia Theatre Times Square. That year, the Downtown Athletic Club and Heisman Trust were also able to resume full control of their Heisman Trophy awards ceremony.",
    location: "Marriott Marquis, 1535 Broadway", latlong: "40.7578398,-73.985675", date: "2001" },
    { category: "sloth", url_1: "http://en.wikipedia.org/wiki/Times_Square_Church", title: "The anti-sloth: Times Square Church opened in response to &ldquo;the physically destitute and spiritually dead people&rdquo; of Times Sq - the pimps, runaways and crack dealers",
    blurb: "The Times Square Church was founded by Pastor David Wilkerson in 1987. At the time, the area was known as a center of X-rated films, strip clubs, prostitution, and drug addiction. Pastor Wilkerson opened the church in response to what he described as &ldquo;the physically destitute and spiritually dead people&rdquo; he saw among the pimps, runaways and crack dealers who populated the area.[2] The Times Square Church briefly held its services in The Town Hall on 43rd Street in Manhattan and then in the Nederlander Theatre on 41st Street. In 1989 the church moved to the former Mark Hellinger Theatre, its current location on 51st Street. The church is headquartered in a theater building originally built by Warner Bros. in 1930 as a movie palace, the Warner Hollywood Theatre, which was later converted to a Broadway venue, the Mark Hellinger Theatre. Times Square Church is an inter-denominational church, with a large number of people representing many nationalities gather to worship together every week. Volunteers from the congregation participate in over forty ministries, ranging from feeding the homeless in New York City to staffing an orphanage in South Africa. A major emphasis at Times Square Church is giving aid to the disadvantaged.",
    location: "237 West 51st Street", latlong: "40.7625894,-73.9848354", date: "1987" },
    { category: "sloth", url_1: "http://www.newyorkhistory.info/42nd-Street/laguardia.html", title: "The anti-sloth: Mayor La Guardia launches a morality campaign on Times Square",
    blurb: "Mayor Fiorello Henry La Guardia determined that the way to political and social salvation lay in moral redemption. After cleaning up what had become the most corrupt police department of any city in America, La Guardia set about to destroy the gambling sites and dens of sexual and alcoholic corruption that had flourished during the previous administration. The legendary La Guardia crackdown on 42nd Street was intended to make an example of those whose moral breakdown had helped to depress the city economically. One by one he personally padlocked the street's notorious burlesque houses, strip joints, game parlors, and houses of prostitution, among them the China Doll, Billy Rose's Diamond Horseshoe, the Latin Quarter, the Versailles, and the Paradise. Such was La Guardia's at times juvenile manner that often, when speeding down the street holding on to the side of a racing fire engine, he'd stick his tongue out at whatever club owners happened to be standing outside, or raise his thumb to his nose and wiggle his fingers. He also removed 42nd Street's traditional trolley cars, because, he angrily declared, they were too provocative, allowing women's dresses to blow above their knees, and besides they slowed down his beloved fire trucks.",
    location: "42nd Street and Broadway", latlong: "40.7567336821428,-73.9886176586151", date: "1929" },
    { category: "wrath", url_1: "http://www.nytimes.com/1989/01/02/nyregion/41-minutes-into-89-city-records-first-homicide.html", title: "First homicide of 1989 took place 41 minutes into the first hours of the year",
    blurb: "A 19-year-old Queens man who was killed in a dispute shortly after he left the raucous New Year's revelry in Times Square was the city's first homicide victim of 1989. His death deaths opened a new page in the police tally of homicides in New York City, a book in which 1988 is believed to have set a grim record. The police said New York had more homicides in 1988 than ever before, surpassing the 1981 record of 1,826.",
    location: "42nd and broadway", latlong: "40.7558315826412,-73.9862680435181", date: "1989" },
    { category: "wrath", url_1: "http://www.consortiumnews.com/archive/story24.html", title: "Tupac Shakur shooting - the Times Square mystery",
    blurb: "On Nov. 30, 1994, Shakur was back in New York City for the sex-abuse trial. Earlier that day, the jury had gotten the case and that night Shakur received an offer to join in a rap recording for $7,000. He needed the money and headed with three friends to Quad Studios in Times Square. After Shakur and his entourage entered the building's lobby, they were attacked from behind. Shakur was shot five times and robbed. After the attackers fled, Shakur and his friends struggled into the elevator and ascended to the ninth floor. A bloodied Shakur staggered into Quad Studios and was surprised to find rival rappers Combs and B.I.G. there. Shakur was convinced that he had been the target of a hit, not a robbery. Shakur's lawyer, Michael Warren, told The Consortium that Shakur believed that the conspiracy also might have involved police officers who considered him a black troublemaker. Shakur's suspicions deepened when he discovered that a police detective, Craig McKernan, who had testified against him in the sex-crime case, was at the scene of the shooting. Shakur claimed that McKernan taunted him about the bullet wounds to the groin. ",
    location: "Quad Studios, 723 7th Ave. 10th Floor", latlong: "40.7599319,-73.9838566", date: "1994" },
    { category: "wrath", url_1: "http://www.davidpietrusza.com/Rothstein.html", url_2: "http://en.wikipedia.org/wiki/Arnold_Rothstein", title: "Arnold Rothstein, man who fixed the 1919 World Series, murdered in Times Square Hotel",
    blurb: "History remembers Arnold Rothstein as the man who fixed the 1919 World Series, an underworld genius. The real-life model for The Great Gatsby's Meyer Wolfsheim and Nathan Detroit from Guys and Dolls, Rothstein was much more—and less—than a fixer of baseball games. Arnold Rothstein was a loan shark, pool shark, bookmaker, thief,fence of stolen property, political fixer, Wall Street swindler, labor racketeer, rumrunner, and mastermind of the modern drug trade. He was murdered in November 1928 murder in a Times Square hotel room. The shooting was allegedly linked to a gambling event that Rothstein had participated in the previous month with several associates and acquaintances. According to underworld folklore, it was a spectacular three-day, high-stakes poker game held somewhere in Manhattan. Rothstein apparently experienced a cold streak with the cards and ended up owing $320,000 at the end of the game. However, Rothstein refused to pay the debt, claiming the game was fixed. The hit was arranged to punish Rothstein for reneging on this debt. Gambler George &ldquo;Hump&rdquo; McManus was arrested for the murder, but later acquitted for lack of evidence. Rothstein's violent death eventually helped bring down Tammany Hall, the nation's biggest political machine—and helped make Fiorello LaGuardia mayor and Franklin Roosevelt president.",
    location: "Park Central Hotel: 870 7th Avenue", latlong: "40.7646907,-73.9812971", date: "1928" },
    { category: "wrath", url_1: "http://www.rapo.com/icrgallery/TimesSquare.htm", title: "Officers on the beat in Times Square in 1965",
    blurb: "This link leads to some great photos from 1965, and give a bit of the lay of the land in 1965.",
    location: "Times Square District", latlong: "40.7607320298553,-73.9844870567322", date: "1965" },
    { category: "wrath", url_1: "http://movies.nytimes.com/movie/103200/Murder-in-Times-Square/overview", title: "Murder In Times Square, movie from 1943",
    blurb: "Edmund Lowe plays Barrymoresque stage actor Cory Williams, who vaingloriously tries to solve a bizarre series of murders. Though the killings take place in the heart of New York, the victims are killed by the venom of a rattlesnake. It turns out that the killing has a vendetta against theater people, and Williams may be next on the list. ",
    location: "Times Square District", latlong: "40.756847459589,-73.9863646030426", date: "1943" },
    { category: "wrath", url_1: "http://www.nostalgiamerchant.biz/Broadway_is_My_Beat/Broadway_is_My_Beat.htm", title: "Broadway Is My Beat, radio show from 1949",
    blurb: "&ldquo;From Times Square to Columbus Circle -- the gaudiest, the most violent, the lonesomest mile in the world. Broadway's my beat.&rdquo; Broadway Is My Beat, was a dark, gritty, radio drama that began airing on CBS February 27, 1949. The series revolved around Times Square homicide detective Danny Clover.",
    location: "Times Square District", latlong: "40.7598949972907,-73.9901947975159", date: "1949" },
    { category: "wrath", url_1: "http://www.crimelife.com/killers/cottingham.html", url_2: "http://forum.goregrish.com/threads/richard-cottingham.2309/", title: "Serial killer in Times Sq: Richard Cottingyham",
    blurb: "Richard Cottingham seemed to be the typical guy-next-door. A former standout athlete in highschool who worked as a computer operator in New York City, Cottingham was married with three children and considered a good family man. In reality he was a sadistic sexual predator who murdered five women from 1977 to 1980. He was nicknamed 'the torso killer', due to his habit of dismembering his victims, usually leaving nothing but a torso behind. In one case, he dismembered two prostitutes in a motel room, taking the hands and heads with him before setting the room on fire. He was eventually convicted of murder in 1981 after being caught fleeing an attempted murder. Officially Cottingham killed 5 people but he claims between 85 and 100 murders. He is currently serving 248 years in prison.",
    location: "Times Square District", latlong: "40.761625936489,-73.9885854721069", date: "1977" },
    { category: "wrath", url_1: "http://www.nytimes.com/1996/12/09/nyregion/bellhop-killed-3-wounded-in-times-square-shooting.html", title: "Bellhop Killed, 3 Wounded in Times Square Shooting",
    blurb: "A shooting on West 43d Street spilled into one of Times Square's new upscale establishments when a stray bullet crashed through the window of a hotel, killing a 50-year-old bellhop working the late shift in its marble and mosaic lobby. The barrage of gunfire -- which sprayed at least eight bullets across the block between Avenue of the Americas and Broadway at 5:23 A.M. -- left three other people injured, said Officer Sara Carpenter, a police spokeswoman. She said that the fight began as an argument inside Le Max restaurant, off the lobby of the newly refurbished Casablanca Hotel, and spilled out onto the street, erupting in gunfire. The shooting was a reminder that while the neighborhood has transformed itself from a seedy, crime-ridden district into a hub of top-name stores, children's theaters and high-end office space, it still is not immune from the violence of the city.",
    location: "Casablanca Hotel, 147 West 43rd Street", latlong: "40.7563551,-73.9854831", date: "1996" }]

    this.map_ready()
    this.set_up_observers()
    
  set_up_observers: () ->
    $(".sins-nav li").click (evt) => this.sins_nav_click(evt)
    $(".sins-nav li").hover (evt) => this.sins_nav_hover(evt)
    
    $("#about_project_trigger").click (evt) => this.about_click(evt)
    $("#overlay").click (evt) => this.about_close(evt)
    
  sins_nav_click: (evt) ->
    evt.preventDefault();
    $("body").addClass "projectactive"

    this.hide_current_category() if @current_category?
    
    $(".active-nav").removeClass "active-nav"
    $(evt.target).addClass "active-nav"
    
    @current_category = $(evt.target).data("category")
    this.show_current_category()
  
  sins_nav_hover: (evt) ->
    li = if evt.target.nodeName is "LI" then evt.target else $(evt.target).parents("li").first()
    $(li).toggleClass "hover-nav"
    
  about_click: (evt) ->
    $("#overlay").fadeIn("fast")
    container = $("#about_project_container")
    container.css "top", "-#{container.outerHeight()}px"
    container.animate({top: 0})
  
  about_close: (evt) ->
    $("#overlay").fadeOut("fast")
    new_top = $("#about_project_container").outerHeight()
    $("#about_project_container").animate({top: "-#{new_top}px"})
  
  hide_current_category: ->
    this.close_open_infowin() if @current_marker
    current_sins = this.get_sins_by_category @current_category
    @current_category = null

    sin.marker.setVisible false for sin in current_sins

  show_current_category: ->
    @gmap.setCenter @bounds.getCenter()
    current_sins = this.get_sins_by_category @current_category
    sin.marker.setVisible true for sin in current_sins
  
  marker_click: (title) ->
    this.close_open_infowin() if @current_marker
    
    sin = this.get_sin_by_title title
    @current_marker = sin
    sin.infoWin.open @gmap, sin.marker
  
  close_open_infowin: ->
    @current_marker.infoWin.close()
    @current_marker = null

  map_ready: ->
    @bounds = new google.maps.LatLngBounds 0,0
    
    # build a marker for each sin
    this.build_marker data for data in @sins_data
    
    @gmap.fitBounds @bounds
    @gmap.setCenter @bounds.getCenter()
    
  build_marker: (data) ->
    coords = data.latlong.split ","
    latlng = new google.maps.LatLng coords[0], coords[1]
    
    data.marker = new google.maps.Marker
      position: latlng
      map: @gmap
      title: data.title
      visible: false
    data.infoWin = new google.maps.InfoWindow 
      content: this.build_infowin_content data
    
    google.maps.event.addListener data.marker, 'click', (event) -> ts_action.marker_click this.title
    
    @bounds.extend latlng
  
  build_infowin_content: (data) ->
    content = "<h3>#{data.title} (#{data.date})</h3>"
    content += "<p>#{data.blurb}</p>"
    content += "<a href='#{data.url_1}' target='_blank'>Further Reading</a>" if data.url_1?
    content += " | <a href='#{data.url_2}' target='_blank'>Further Reading</a>" if data.url_2?
    return content
  
  get_sins_by_category: (category_name) ->
    _.select @sins_data, (data) -> if data.category == category_name then data else null
  
  get_sin_by_title: (title) ->
    _.detect @sins_data, (data) -> if data.title == title then data else null

root.TimesSinsData = TimesSinsData